### ISSUE TITLE
`added` contains existing paths

### ISSUE THREAD

**Issue by Marsup** [lukascivil/json-difference#39]
Hi,

I'd like to understand if something is the normal behavior of this module or if this is a bug.

Getting a diff using something like this:
```js
getDiff({ foo: { bar: true } }, { foo: {} })
```

Returns this as a result:
```js
{
  added: [ [ 'foo', {} ] ],
  removed: [ [ 'foo/bar', true ] ],
  edited: []
}
```

While I understand the `removed` part, why would it consider `foo` to be added?

Thanks!

**Comment by lukascivil** [comment]
@Marsup you're right, its a bug. I'm looking for a way to solve the problem! It's possible that a break change makes sense here.

**Comment by lukascivil** [comment]
I think that solves https://github.com/lukascivil/json-difference/pull/40

**Comment by lukascivil** [comment]
Hey @Marsup, could you perform some operations here http://jsondifference.lukascivil.com.br/ and validate if everything is OK? 

The code uploaded in this link is the master.
