### ISSUE TITLE
rawgit.com link is broken

### ISSUE THREAD

**Issue by asvarga** [lukascivil/json-difference#61]
The [https://rawgit.com/lukascivil/jsondiffer/master/dist.browser/json-difference.mjs](https://rawgit.com/lukascivil/jsondiffer/master/dist.browser/json-difference.mjs) link mentioned in the README "Installation" section is broken. I'm guessing this it just the result of the [broken workflow](https://github.com/lukascivil/json-difference/actions/workflows/npm-publish-github-packages.yml).

As a workaround, I'm using a non-`master` link like [https://rawgit.com/lukascivil/json-difference/1.9.1/dist.browser/json-difference.mjs](https://rawgit.com/lukascivil/json-difference/1.9.1/dist.browser/json-difference.mjs).

**Comment by lukascivil** [comment]
@asvarga I changed the deployment to AWS S3., see if it can help you

```
<script type="module">
  // https://json-difference.s3.amazonaws.com/<a.b.c>/json-difference-<a.b.c>.mjs

  import { getDiff } from 'https://json-difference.s3.amazonaws.com/1.16.0/json-difference-1.16.0.mjs'
</script>
```
