### ISSUE TITLE
move vite to devDependencies of json-difference

### ISSUE THREAD

**Issue by zxkane** [lukascivil/json-difference#71]
I don't see any module importing from vite in the source of json-difference. It helps the downstream projects to exclude the vite as a transit dependency.

**Comment by lukascivil** [comment]
@zxkane thx for your help! What happened was that the "@nx/dependency-checks" guided me to add the dependency and it should be added to devDependency and skipped in eslint config.

This https://github.com/lukascivil/json-difference/pull/72 should adjust.

**Comment by lukascivil** [comment]
@zxkane Can you confirm that everything is ok now?

**Comment by zxkane** [comment]
> @zxkane Can you confirm that everything is ok now?

Yes. When using `1.16.1`, I don't see `vite` in the dependencies any more.
